LogLevel: INFO
Modules:
  PilotSkill:
    Enabled: True
  ReleaseSkill:
    Enabled: True
  ScuttleSkill:
    Enabled: True
  BasicCraftTargeter:
    Enabled: True
  RemoteSignSkill:
    Enabled: True
  TrimSkills:
    Enabled: True